server:
  port: 9527

  thymeleaf:
    #    prefix: file:/home/java/templates/
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 16MB

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    database: 0
    lettuce:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0